import csv, re
from collections import defaultdict, Counter

def cleanOccupation(trade):
    if not trade or trade.strip() == "" or trade == "-" or re.match(r"^(mrs\.?|miss\.?|mr\.?|thos\.?|jas\.?|wm\.?|saml\.?|john|geo\.?|chas\.?|hy\.?|richd\.?|harry|ernest|fredk\.?|arthur|edwd\.?|walt\.?|david|danl\.?|benj\.?|stepn\.?|iss e|ltd\.?|limited|co\.?|& co\.?|co\.? ltd\.?|ld\.?|henry|joseph|albert|reginald|harold|alfred|frank|edward|herbert|edwin|fred|norman|ivor|stanley|leslie|sidney|horace|edgar|lewis|percy|wilfred|bernard|eric|clifford|trevor)$", trade.strip(), re.I):
        return "Residence / Private"

    clean = trade.strip()
    clean = re.sub(r"\bg[\.\s]*w[\.\s]*r[\.\s]*", "G.W.R. ", clean, flags=re.I)
    clean = re.sub(r"G\.W\.R\.\s*[\.,]+", "G.W.R. ", clean, flags=re.I)
    clean = re.sub(r"\s+", " ", clean).strip()
    clean = re.sub(r"G\.W\.R\.\s*$", "G.W.R.", clean, flags=re.I)
    clean = re.sub(r"\bgov\.?\s+offcl\b", "Government Official", clean, flags=re.I)
    clean = re.sub(r"\bdk\s+police\b", "Dock Police", clean, flags=re.I)
    clean = re.sub(r"\bldg\s+ho\b", "Lodging House", clean, flags=re.I)
    clean = re.sub(r"\bdrapers\s+collctr\b", "Drapers Collector", clean, flags=re.I)
    clean = re.sub(r"\bgas\s+inspct\b", "Gas Inspector", clean, flags=re.I)
    clean = re.sub(r"\bblrmr\b", "Boilermaker", clean, flags=re.I)
    clean = re.sub(r"\bcustom\s+offr\b", "Custom Officer", clean, flags=re.I)
    clean = re.sub(r"\bglass\s+(wrkr|wk)\b", "Glass Worker", clean, flags=re.I)
    clean = re.sub(r"\bice\s+cream\s+vendr\b", "Ice Cream Vendor", clean, flags=re.I)
    clean = re.sub(r"\bcoal\s+tipr\b", "Coal Tipper", clean, flags=re.I)
    clean = re.sub(r"\bdentst\b", "Dentist", clean, flags=re.I)
    clean = re.sub(r"\bbus\s+drvi\b", "Bus Driver", clean, flags=re.I)
    clean = re.sub(r"\bwagon\s+rp\b", "Wagon Repairer", clean, flags=re.I)
    clean = re.sub(r"\b(electcn|electrn|elect|elct)\b", "Electrician", clean, flags=re.I)
    clean = re.sub(r"\bflour\s+packr\b", "Flour Packer", clean, flags=re.I)
    clean = re.sub(r"\broad\s+swp\b", "Road Sweeper", clean, flags=re.I)
    clean = re.sub(r"\b(ironwor|ironwrkr|ironworkr|iworker|irn\s+worker)\b", "Ironworker", clean, flags=re.I)
    clean = re.sub(r"\bbuilding\s+contr\s*&\s*engnrs\b", "Building Contractors and Engineers", clean, flags=re.I)
    clean = re.sub(r"\bsales\s+drvr\b", "Sales Driver", clean, flags=re.I)
    clean = re.sub(r"\btbeworker\b", "Tubeworker", clean, flags=re.I)
    clean = re.sub(r"\bshoe\s+repr\b", "Shoe Repairer", clean, flags=re.I)
    clean = re.sub(r"\bsteehvorkr\b", "Steelworker", clean, flags=re.I)
    clean = re.sub(r"\bcrane\s+dr\b", "Crane Driver", clean, flags=re.I)
    clean = re.sub(r"\belec\s+engineer\b", "Electrical Engineer", clean, flags=re.I)
    clean = re.sub(r"\bstl\s+worker\b", "Steel Worker", clean, flags=re.I)
    clean = re.sub(r"\bmotor\s+(drvr|dr)\b", "Motor Driver", clean, flags=re.I)
    clean = re.sub(r"\bins\s+agt\b", "Insurance Agent", clean, flags=re.I)
    clean = re.sub(r"\bpostmn\b", "Postman", clean, flags=re.I)
    clean = re.sub(r"\bcivil\s+serv(t|nt)\b", "Civil Servant", clean, flags=re.I)
    clean = re.sub(r"\bdk\s+worker\b", "Dock Worker", clean, flags=re.I)
    clean = re.sub(r"\btrmr\b", "Trimmer", clean, flags=re.I)
    clean = re.sub(r"\bbricklayr\b", "Bricklayer", clean, flags=re.I)
    clean = re.sub(r"\bsupt\.?\b", "Superintendent", clean, flags=re.I)
    clean = re.sub(r"\bupholstr\b", "Upholsterer", clean, flags=re.I)
    clean = re.sub(r"\bloco\s+driver\b", "Locomotive Driver", clean, flags=re.I)
    clean = re.sub(r"\bclrk\b", "Clerk", clean, flags=re.I)
    clean = re.sub(r"\b(steelworkr|steehvorkr|stlwrkr)\b", "Steelworker", clean, flags=re.I)
    clean = re.sub(r"\bship\s+brkr\b", "Ship Broker", clean, flags=re.I)
    clean = re.sub(r"\bfitters\s+hlpr\b", "Fitters Helper", clean, flags=re.I)
    clean = re.sub(r"\bmarbl\s+polshr\b", "Marble Polisher", clean, flags=re.I)
    clean = re.sub(r"\bcab\s+proprtr\b", "Cab Proprietor", clean, flags=re.I)
    clean = re.sub(r"\bmonu\.?\s+mason\b", "Monumental Mason", clean, flags=re.I)
    clean = re.sub(r"\brailwymn\b", "Railwayman", clean, flags=re.I)
    clean = re.sub(r"\brly\s+foreman\b", "Railway Foreman", clean, flags=re.I)
    clean = re.sub(r"\brly\s+inspt\b", "Railway Inspector", clean, flags=re.I)
    clean = re.sub(r"\btram\s+inspt\b", "Tram Inspector", clean, flags=re.I)
    clean = re.sub(r"\binspt\b", "Inspector", clean, flags=re.I)
    clean = re.sub(r"\bironw6rker\b", "Ironworker", clean, flags=re.I)
    clean = re.sub(r"\bgeneral\s+grocr\b", "General Grocer", clean, flags=re.I)
    clean = re.sub(r"\blaborr\b", "Labourer", clean, flags=re.I)
    clean = re.sub(r"\bpier\s+mastr\b", "Pier Master", clean, flags=re.I)
    clean = re.sub(r"\bhouse\s+fur\b", "House Furnisher", clean, flags=re.I)
    clean = re.sub(r"\bhatter\s*,\s*,\s*etc\b", "Hatter, etc.", clean, flags=re.I)
    clean = re.sub(r"\bboot\s+manuftrs\b", "Boot Manufacturers", clean, flags=re.I)
    clean = re.sub(r"\bphotogrpr\b", "Photographer", clean, flags=re.I)
    clean = re.sub(r"\bmotormn\b", "Motorman", clean, flags=re.I)
    clean = re.sub(r"\btug\s+drvr\b", "Tug Driver", clean, flags=re.I)
    clean = re.sub(r"\belec\.?\s+eng\b", "Electrical Engineer", clean, flags=re.I)
    clean = re.sub(r"\bcoachmn\b", "Coachman", clean, flags=re.I)
    clean = re.sub(r"\brway\s+ganger\b", "Railway Ganger", clean, flags=re.I)
    clean = re.sub(r"\beng\.?\s+drvr\.?\s+g\.?w\.?r\.?\b", "Engine Driver G.W.R.", clean, flags=re.I)
    clean = re.sub(r"\bwoodtrnr\b", "Woodturner", clean, flags=re.I)
    clean = re.sub(r"\btel\.?\s+clerk\b", "Telephone Clerk", clean, flags=re.I)
    clean = re.sub(r"\bcellrmn\b", "Cellarman", clean, flags=re.I)
    clean = re.sub(r"\bstrkr\b", "Striker", clean, flags=re.I)
    clean = re.sub(r"\b(l;ab|labour[\x27\x22\x60]?r)\b", "Labourer", clean, flags=re.I)
    clean = re.sub(r"\btail;ors\b", "Tailors", clean, flags=re.I)
    clean = re.sub(r"\bbrewerr\b", "Brewer", clean, flags=re.I)
    clean = re.sub(r"\bprovision\s+merchanty\b", "Provision Merchant", clean, flags=re.I)
    clean = re.sub(r"\bglass\s+blr\b", "Glassblower", clean, flags=re.I)
    clean = re.sub(r"\btransp[\x27\x22\x60]?t\s+w[\x27\x22\x60]?r\b", "Transport Worker", clean, flags=re.I)
    clean = re.sub(r"\bcr\.?\s*driver\b", "Crane Driver", clean, flags=re.I)
    clean = re.sub(r"\btr[\x27\x22\x60]?mmer\b", "Trimmer", clean, flags=re.I)
    clean = re.sub(r"\bhse\s+craft\s+mistress\b", "House Craft Mistress", clean, flags=re.I)
    clean = re.sub(r"\bcanteen\s+stwd\b", "Canteen Steward", clean, flags=re.I)
    clean = re.sub(r"\biron\s*&\s*metal\s+mcht\s+and\s+marine\s+stores\b", "Iron & Metal Merchant and Marine Stores", clean, flags=re.I)
    clean = re.sub(r"\biworker\s*&\s*shop\b", "Ironworker and Shop", clean, flags=re.I)
    clean = re.sub(r"\bnews\s*&\s*hairdr\b", "News and Hairdresser", clean, flags=re.I)
    clean = re.sub(r"\bturf\s+acnt\b", "Turf Accountant", clean, flags=re.I)
    clean = re.sub(r"\bahopkeeper\b", "Shopkeeper", clean, flags=re.I)
    clean = re.sub(r"\btime\s+kp\b", "Timekeeper", clean, flags=re.I)
    clean = re.sub(r"\bpump\s+attd?t\b", "Pump Attendant", clean, flags=re.I)
    clean = re.sub(r"\bcoal\s+tmr\b", "Coal Trimmer", clean, flags=re.I)
    clean = re.sub(r"\bblksth\b", "Blacksmith", clean, flags=re.I)
    clean = re.sub(r"\bschool\s+teach\b", "School Teacher", clean, flags=re.I)
    clean = re.sub(r"\bshop\s+ft[\x27\x22\x60]?rs\b", "Shop Fitters", clean, flags=re.I)
    clean = re.sub(r"\binsurnc\s+agt\b", "Insurance Agent", clean, flags=re.I)
    clean = re.sub(r"\bhead\s+waitr\b", "Head Waiter", clean, flags=re.I)
    clean = re.sub(r"\brailwaymn\b", "Railwayman", clean, flags=re.I)
    clean = re.sub(r"\bbootmkrs\b", "Bootmakers", clean, flags=re.I)
    clean = re.sub(r"\bgreengrcrs\b", "Greengrocers", clean, flags=re.I)
    clean = re.sub(r"\bpolice\s+sgt\b", "Police Sergeant", clean, flags=re.I)
    clean = re.sub(r"\btobacnst\b", "Tobacconist", clean, flags=re.I)
    clean = re.sub(r"\bbuilders\s+yd\b", "Builders Yard", clean, flags=re.I)
    clean = re.sub(r"\bsecty\b", "Secretary", clean, flags=re.I)
    clean = re.sub(r"\bgenl\s+dealer\b", "General Dealer", clean, flags=re.I)
    clean = re.sub(r"\bcellarmn\b", "Cellarman", clean, flags=re.I)
    clean = re.sub(r"\btravellr\b", "Traveller", clean, flags=re.I)
    clean = re.sub(r"\bcycle\s+repr\b", "Cycle Repairer", clean, flags=re.I)
    clean = re.sub(r"\benginemn\b", "Engineman", clean, flags=re.I)
    clean = re.sub(r"\bpipe\s+fittr\b", "Pipe Fitter", clean, flags=re.I)
    clean = re.sub(r"\bstocktkr\b", "Stocktaker", clean, flags=re.I)
    clean = re.sub(r"\bwheelwgt\b", "Wheelwright", clean, flags=re.I)
    clean = re.sub(r"\bwardrobe\s+dlr\b", "Wardrobe Dealer", clean, flags=re.I)
    clean = re.sub(r"\bdecor[\x27\x22\x60]?tr\b", "Decorator", clean, flags=re.I)
    clean = re.sub(r"\bboilermk\b", "Boilermaker", clean, flags=re.I)
    clean = re.sub(r"\bpltlyr\b", "Platelayer", clean, flags=re.I)
    clean = re.sub(r"\bglass\s+wks\b", "Glass Works", clean, flags=re.I)
    clean = re.sub(r"\bins\.?\s+superintendent\b", "Insurance Superintendent", clean, flags=re.I)
    clean = re.sub(r"\bgenl\.?\s+shop\b", "General Shop", clean, flags=re.I)
    clean = re.sub(r"\bironwkr\b", "Ironworker", clean, flags=re.I)
    clean = re.sub(r"\bstlwkr\b", "Steelworker", clean, flags=re.I)
    clean = re.sub(r"wkr\b", "worker", clean, flags=re.I)

    clean = re.sub(r"\blabr\b", "Labourer", clean, flags=re.I)
    clean = re.sub(r"\bdvr\b", "Driver", clean, flags=re.I)
    clean = re.sub(r"\bptr\b", "Painter", clean, flags=re.I)
    clean = re.sub(r"\bclk\b", "Clerk", clean, flags=re.I)
    clean = re.sub(r"\btrm\b", "Trimmer", clean, flags=re.I)
    clean = re.sub(r"\bbricklyr\b", "Bricklayer", clean, flags=re.I)
    clean = re.sub(r"\bcarptr\b", "Carpenter", clean, flags=re.I)
    clean = re.sub(r"\beng dvr\b", "Engine Driver", clean, flags=re.I)

    clean = re.sub(r"\b(g\.?p\.?o\.?)\b\.?", "G.P.O.", clean, flags=re.I)
    def cap(m):
        txt = m.group(0)
        if txt.upper() == "G.W.R.": return "G.W.R."
        if txt.upper() == "G.P.O.": return "G.P.O."
        return txt.capitalize()
    clean = re.sub(r"\w\S*", cap, clean)
    return clean

counts = Counter()
raw_map = defaultdict(set)
with open("data.csv", "r", encoding="utf-8") as f:
    r = csv.reader(f)
    next(r)
    for row in r:
        if len(row) >= 7:
            raw = row[6].strip()
            cleaned = cleanOccupation(raw)
            counts[cleaned] += 1
            raw_map[cleaned].add(raw)

print(f"Total Unique Cleaned Trades: {len(counts)}")

oddities = []
for cleaned, freq in counts.items():
    raws = list(raw_map[cleaned])
    if any(x in cleaned for x in ["Do", "Ditto", "—", "-", "&C", ",", "[", "]", "&c"]) or len(cleaned) <= 4 or "Lab" in cleaned or "Eng" in cleaned or "Agt" in cleaned or "Mer" in cleaned:
        oddities.append((cleaned, freq, raws[:3]))

oddities.sort(key=lambda x: x[1], reverse=True)
print("\n--- Key Trade Variations & Oddities Currently Generated ---")
for item in oddities[:60]:
    print(f"  {repr(item[0]):<35} (Count: {item[1]:<5}) <- Raw samples: {item[2]}")
